### ISSUE TITLE
no tag/GitHub release for 0.2.3

### ISSUE THREAD

**Issue by FelixSchwarz** [yaroslaff/showcert#3]
I found a pypi release for version 0.2.3 but no corresponding git tag/GitHub release. Would you mind adding that?

(I'm about to submit a package for showcert to Fedora and at first I was confused which version is the latest.)

**Comment by yaroslaff** [comment]
Thank you! Added tag for latest release 0.2.3.

**Comment by FelixSchwarz** [comment]
Great, thank you :-)
