### ISSUE TITLE
v0.2.7 doesn't run on RHEL9

### ISSUE THREAD

**Issue by deajan** [yaroslaff/showcert#7]
Hello,

Running on Almalinux 9.5 with latest updates, I installed showcert via pip.
Here's my output when trying to run the binary without any arguments:
```
Traceback (most recent call last):
  File "/usr/local/bin/showcert", line 5, in <module>
    from showcert.showcert import main
  File "/usr/local/lib/python3.9/site-packages/showcert/showcert.py", line 12, in <module>
    from OpenSSL.crypto import FILETYPE_PEM, FILETYPE_TEXT, load_certificate, \
  File "/usr/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1579, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1598, in X509StoreFlags
    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
```

**Comment by yaroslaff** [comment]
Hello!

Could you please show `pip freeze` output?

**Comment by deajan** [comment]
Sure:

Python 3.9.21 pip output:
```
acme==2.11.0
certbot==2.11.0
certifi==2024.12.14
cffi==1.14.5
chardet==4.0.0
ConfigArgParse==1.7
configobj==5.0.6
cryptography==44.0.0
dbus-python==1.2.18
distro==1.5.0
gpg==1.15.1
idna==2.10
importlib-metadata==4.12.0
iotop==0.6
josepy==1.14.0
libcomps==0.1.18
nftables==0.1
parsedatetime==2.6
pem==23.1.0
perf==0.1
ply==3.11
pycparser==2.20
PyGObject==3.40.1
pyOpenSSL==21.0.0
pyRFC3339==1.1
PySocks==1.7.1
python-dateutil==2.8.1
python-linux-procfs==0.7.3
pytz==2021.1
pyudev==0.22.0
requests==2.25.1
rpm==4.16.1.3
selinux==3.6
sepolicy==3.6
setools==4.4.4
showcert==0.2.9
six==1.15.0
systemd-python==234
urllib3==1.26.5
zipp==3.20.1
```

**Comment by yaroslaff** [comment]
Thank you for report!

Looks like latest cryptography==44.0.0 is not compatible with older pyOpenSSL==21.0.0, I bumped requirements in new showcert 0.2.11, you can try it.

Also, recommended (more reliable) way to install showcert is via pipx:
~~~
dnf install python3-pip
pip3 install pipx
pipx install showcert
~~~

This would keep all required packages inside showcert virtualenv (not mixing it with system-wide installed packages).

**Comment by FelixSchwarz** [comment]
Hey @deajan, getting showcert to run only with native packages probably means we need to replace hatchling with `setup.cfg` which should be a pretty simple task. Also I would welcome a RHEL 9-compatible source code. If that happens, let me know - I'll be happy to push a version to Fedora EPEL 9 which you could use with Alma.

**Comment by deajan** [comment]
Updated to latest release, works ok, thank you.
Still it doesn't fetch the CA certificate when using letsencrypt, only the user cert and the intermediate CA.

As for RHEL, since a simple pip install works, I don't think it matters to make RPMs.

**Comment by yaroslaff** [comment]
showcert fetches cert chain that website gives (and this is website cert + maybe intermediate cert, but no CA cert on server). 
If you need CA cert, you probably already have it on your computer (in trusted CA list), no need to take it from remote server.

How to find it (I use latest 0.2.12):

```shell
$ showcert --chain -o ext github.com
...
IP: 140.82.121.3
Names: USERTrust ECC Certification Authority
notBefore: 2019-03-12 00:00:00 (2114 days old)
notAfter: 2028-12-31 23:59:59 (1468 days left)
Issuer: C=GB ST=Greater Manchester L=Salford O=Comodo CA Limited CN=AAA Certificate Services
Fingerprint (sha256): A6:CF:64:DB:B4:C8:D5:FD:19:CE:48:89:60:68:DB:03:B5:33:A8:D1:33:6C:62:56:A8:7D:00:CB:B3:DE:F3:EA
Subject KI: 3A:E1:09:86:D4:CF:19:C2:96:76:74:49:76:DC:E0:35:C6:63:63:9A
Authority KI: A0:11:0A:23:3E:96:F1:07:EC:E2:AF:29:EF:82:A5:7F:D0:30:A4:B4
Tags: [CA] [CHAIN-VERIFIED]
```
We need `-o ext` for extended output format to see AKI/SKI to trace full certificate chain.

Last certificate in chain has Authority Key Identifier:  `A0:11:0A:23:3E:96:F1:07:EC:E2:AF:29:EF:82:A5:7F:D0:30:A4:B4`.
You need to find CA cert which has SKI equal to AKI of this certificate.

All system CA certs compiled are usually in file `/etc/ssl/certs/ca-certificates.crt`
Next step: `showcert -i -c -o ext /etc/ssl/certs/ca-certificates.crt | less` and search for this AKI and we find:

```
Names: AAA Certificate Services
notBefore: 2004-01-01 00:00:00 (7663 days old)
notAfter: 2028-12-31 23:59:59 (1468 days left)
Issuer: C=GB ST=Greater Manchester L=Salford O=Comodo CA Limited CN=AAA Certificate Services
Fingerprint (sha256): D7:A7:A0:FB:5D:7E:27:31:D7:71:E9:48:4E:BC:DE:F7:1D:5F:0C:3E:0A:29:48:78:2B:C8:3E:E0:EA:69:9E:F4
Subject KI: A0:11:0A:23:3E:96:F1:07:EC:E2:AF:29:EF:82:A5:7F:D0:30:A4:B4
Tags: [SELF-SIGNED] [CA]
```
As you see, SKI of this cert matches AKI of last certificate in chain we get from github, so github.com is signed by this CA cert.

or we can find it in this file:
```
$ showcert -i -o ext /etc/ssl/certs/Comodo_AAA_Services_root.pem
Names: AAA Certificate Services
notBefore: 2004-01-01 00:00:00 (7663 days old)
notAfter: 2028-12-31 23:59:59 (1468 days left)
Issuer: C=GB ST=Greater Manchester L=Salford O=Comodo CA Limited CN=AAA Certificate Services
Fingerprint (sha256): D7:A7:A0:FB:5D:7E:27:31:D7:71:E9:48:4E:BC:DE:F7:1D:5F:0C:3E:0A:29:48:78:2B:C8:3E:E0:EA:69:9E:F4
Subject KI: A0:11:0A:23:3E:96:F1:07:EC:E2:AF:29:EF:82:A5:7F:D0:30:A4:B4
Tags: [SELF-SIGNED] [CA]
```

**Comment by deajan** [comment]
Indeed, the CA is already in the trusted bundle, but I wanted to use showcert to fetch the CA too, in order to get the full trust chain, which doesn't work:

```
[root@myserver]# showcert --chain -o pem -o ext mydomain:443
IP: 127.0.0.1
Names: mydomain
notBefore: 2024-12-16 07:43:57 (8 days old)
notAfter: 2025-03-16 07:43:56 (81 days left)
Issuer: C=US O=Let's Encrypt CN=E6
Fingerprint (sha256): 36:8F:1A:78:45:31:AE:E8:84:8D:7F:4D:2D:1B:6D:28:72:8A:33:AD:52:A2:69:ED:C7:EB:C6:DF:9D:C1:58:F9
SKI (sha256): DB:9F:1C:9F:65:41:89:D5:81:76:99:F5:0E:4F:AE:B2:D8:2F:DC:DF
AKI (sha256): 93:27:46:98:03:A9:51:68:8E:98:D6:C4:42:48:DB:23:BF:58:94:D2
Tags: [CHAIN-VERIFIED]

IP: 127.0.0.1
Names: E6
notBefore: 2024-03-13 00:00:00 (286 days old)
notAfter: 2027-03-12 23:59:59 (808 days left)
Issuer: C=US O=Internet Security Research Group CN=ISRG Root X1
Fingerprint (sha256): 76:E9:E2:88:AA:FC:0E:37:F4:39:0C:BF:94:6A:AD:99:7D:5C:1C:90:1B:3C:E5:13:D3:D8:FA:DB:AB:E2:AB:85
SKI (sha256): 93:27:46:98:03:A9:51:68:8E:98:D6:C4:42:48:DB:23:BF:58:94:D2
AKI (sha256): 79:B4:59:E6:7B:B6:E5:E4:01:73:80:08:88:C8:1A:58:F6:E9:9B:6E
Tags: [CA] [CHAIN-VERIFIED]
```

When using another tool, I get the full CA path, see https://github.com/pete911/certinfo/issues/41

Anyway, thanks.
